version: '2'

services:
  frontend:
    build: frontend
    ports:
      - "3000:3000"
    container_name: front-container
    restart: always

  backend:
    build: backend
    ports:
      - "8080:8080"
    container_name: back-container
    restart: always
    links:
      - db

  db:
    build: db
    container_name: database-container
    restart: always

