export const SET_USER = 'PROFILE_ACTION:SET_USER';
export const SET_USER_IMG = 'PROFILE_ACTION:SET_USER_IMG';
export const SET_USERNAME = 'PROFILE_ACTION:SET_USERNAME';
export const SET_USER_STATUS = 'PROFILE_ACTION:SET_USER_STATUS';
